version: "3.8"

services:
  app:
    build: ./docker/php
    volumes:
      - ./backend:/work/web

  web:
    build: ./docker/nginx
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./backend:/work/web
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    volumes:
      - ./docker/mysql/my.conf:/etc/mysql/conf.d/my.conf
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ph5-aws
      - TZ=Asia/Tokyo
