name: Deploy AWS
on:
  push:
    branches:
      - main
env:
  ROLE_TO_ASSUME: arn:aws:iam::771105554154:role/GitHubActions
  FRONT_BACKET_NAME: ph5aws-web
  CLOUDFRONT_ID: E1S8MYVW5X2EBS
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v1
          with:
            role-to-assume: ${{ env.ROLE_TO_ASSUME }}
            role-session-name: github-actions-${{ github.run_ad }}
            aws-region: ap-northeast-1

        - name: Get AWS Account
          run: aws sts get-caller-identity

        - name: Build
          run: |
            cd front
            cp .env.aws .env
            rm .env.aws
            rm .env.dev
            yarn install
            yarn build

        - name: Deploy
          run: |
            aws s3 sync front/build/ s3://${{ env.FRONT_BACKET_NAME }}/ --delete --exact-timestamps
            aws cloudfront create-invalidation --distribution-id ${{ env.CLOUDFRONT_ID }} --paths "/*"